In [1]:
L = list(range(10))

In [2]:
L?

Type:        list
String form: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Length:      10
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [3]:
L??

Type:        list
String form: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Length:      10
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [4]:
L2 = [str(c) for c in L]

In [5]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True,"2", 3.0, 4]

In [9]:
[type(item) for item in L3]

[bool, str, float, int]

In [10]:
L3?

Type:        list
String form: [True, '2', 3.0, 4]
Length:      4
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [11]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(A)

array.array

In [13]:
A?

Type:        array
String form: array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Length:      10
Docstring:  
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes 
    'b'         signed integer     1 
    'B'         unsigned integer   1 
    'u'         Unicode character  2 (see note) 
    'h'         signed integer     2 
    'H'         unsigned integer   2 
    'i'         signed integer     2 
    'I'         unsigned integer   2 
    'l'         signed integer     4 
    'L'         unsigned intege

In [1]:
import numpy as np  # import numpy

In [2]:
#integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
#upcast
np.array([1.5, 4, 2, 5, 3])

array([1.5, 4. , 2. , 5. , 3. ])

In [4]:
# set data type
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [5]:
# nested list results in multidimensional arrays
np.array([range(i, i + 3) for i in  [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
# Create 3x5 floating array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Create a 3x5 arry filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
# Create 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.23641493, 0.13820041, 0.14768883],
       [0.51778927, 0.52128444, 0.43960134],
       [0.32728025, 0.30895117, 0.67141029]])

In [22]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.64841089, -1.33822876, -0.12000792],
       [ 0.34544887, -0.03760509,  0.59514449],
       [ 0.17440362, -0.74298404, -0.34103748]])

In [23]:
# Create a 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [3, 1, 3],
       [0, 5, 3]])

In [24]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

In [27]:
np.empty(3)

array([1., 1., 1.])

In [40]:
import numpy as np 
np.random.seed(0)

x1 = np.random.randint(10, size=6) # One dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three dimensional aray

In [45]:
print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12


In [46]:
print("dtype: ", x3.dtype)

dtype:  int32


In [48]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes:  240 bytes
